name: RecycloBot CI

on:
  push:
    branches: [ feature/recyclobot, main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black isort
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install transformers datasets google-generativeai opencv-python pyarrow
        # Note: In real PR, would install lerobot properly
        # pip install -e ".[feetech]"
    
    - name: Run code formatters (check mode)
      run: |
        black --check --diff recyclobot/
        isort --check-only --diff recyclobot/
    
    - name: Run tests
      run: |
        pytest tests/test_planner_json.py -v
        pytest tests/test_logger_roundtrip.py -v
    
    - name: Test import
      run: |
        python -c "import recyclobot; print(f'RecycloBot version: {recyclobot.__version__}')"
        python -c "from recyclobot.control.skill_runner import SkillRunner; print('Imports OK')"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint mypy
    
    - name: Run flake8
      run: |
        flake8 recyclobot/ --count --select=E9,F63,F7,F82 --show-source --statistics || true
        flake8 recyclobot/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run pylint
      run: |
        pylint recyclobot/ --disable=all --enable=E || true

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Security Scan
      uses: gaurav-nelson/bandit-action@v1
      with:
        path: "recyclobot/"
        level: medium
        confidence: medium
        exit_zero: true

  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check documentation
      run: |
        # Check that all documentation files exist
        test -f README_RECYCLOBOT.md
        test -f docs/architecture.md
        echo "Documentation files present ✓"