name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov pytest-xdist
    
    - name: Run CPU tests
      run: |
        # Run tests that don't require GPU
        pytest tests/ -m "not gpu" -v --cov=recyclobot --cov-report=xml
        
        # Check that tests were actually collected and run
        TEST_COUNT=$(pytest tests/ -m "not gpu" --collect-only -q | grep -c "test")
        if [ "$TEST_COUNT" -eq 0 ]; then
          echo "ERROR: No CPU tests were collected!"
          exit 1
        fi
        echo "Collected $TEST_COUNT CPU tests"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  gpu-test:
    runs-on: ubuntu-latest
    # Only run GPU tests on main branch or when explicitly requested
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'gpu-test')
    
    container:
      image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
      options: --gpus all
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y git build-essential
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov
    
    - name: Run GPU tests
      run: |
        # Run GPU-specific tests
        pytest tests/ -m "gpu" -v --cov=recyclobot --cov-report=xml
        
        # If no GPU tests exist yet, that's OK - just note it
        TEST_COUNT=$(pytest tests/ -m "gpu" --collect-only -q | grep -c "test" || echo "0")
        if [ "$TEST_COUNT" -eq 0 ]; then
          echo "Note: No GPU tests found (this is OK if GPU tests haven't been written yet)"
        else
          echo "Ran $TEST_COUNT GPU tests"
        fi

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
    
    - name: Run Black
      run: black --check --diff .
      continue-on-error: true
    
    - name: Run isort
      run: isort --check-only --diff .
      continue-on-error: true
    
    - name: Run flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      continue-on-error: true